<?php


class GalleryMapper extends DatabaseV2
{

    public function __construct()
    {
        $mapper = new DatabaseV2Mapper("gallery",
            new DatabaseV2MapperCol("id", "id", "i", true, true),
            new DatabaseV2MapperColLeftJoin("files_id", "file", "files", "id", "id"),
            new DatabaseV2MapperCol("ord", "ord", "i", false, false, 0),
            new DatabaseV2MapperColLeftJoin("tag", "tag", "tags", "id", "id"));

        parent::__construct($mapper);
    }

    public function selectAll($orderDesc = true)
    {
        return parent::selectAll(!$orderDesc); // TODO: Change the autogenerated stub
    }

    /**
     * @param Gallery $gallery
     * @return DatabaseV2Result
     * @throws Exception
     */
    public function insert($gallery)
    {
        $insert = parent::insert($gallery);

        $gallery->id = $insert->lastInsertId;
        $gallery->ord = $insert->lastInsertId;
        $this->updateByPk($gallery);

        return $insert;

    }

    public function deleteByFilesId($primaryKeyValue)
    {
        $sql = "DELETE FROM ".$this->mapper->tableName." WHERE files_id = ?";
        return $this->query($sql, "i", $primaryKeyValue);
    }

    /**
     * @return Gallery
     */
    protected function getEntityInstance() {
        return new Gallery();
    }

}

